//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TraxPark.Srv_TraxPark {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DCGTECSoap", Namespace="http://localhost/WebService")]
    public partial class DCGTEC : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Man_ConfiguracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Man_EstacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Man_TipoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Man_PerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback Man_UsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Traer_ConfiguracionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Traer_EstacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Traer_TipoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Traer_UsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback Traer_TarifaOperationCompleted;
        
        private System.Threading.SendOrPostCallback LOGINOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DCGTEC() {
            this.Url = global::TraxPark.Properties.Settings.Default.TraxPark_Srv_TraxPark_DCGTEC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Man_ConfiguracionCompletedEventHandler Man_ConfiguracionCompleted;
        
        /// <remarks/>
        public event Man_EstacionCompletedEventHandler Man_EstacionCompleted;
        
        /// <remarks/>
        public event Man_TipoUsuarioCompletedEventHandler Man_TipoUsuarioCompleted;
        
        /// <remarks/>
        public event Man_PerfilCompletedEventHandler Man_PerfilCompleted;
        
        /// <remarks/>
        public event Man_UsuarioCompletedEventHandler Man_UsuarioCompleted;
        
        /// <remarks/>
        public event Traer_ConfiguracionCompletedEventHandler Traer_ConfiguracionCompleted;
        
        /// <remarks/>
        public event Traer_EstacionCompletedEventHandler Traer_EstacionCompleted;
        
        /// <remarks/>
        public event Traer_TipoUsuarioCompletedEventHandler Traer_TipoUsuarioCompleted;
        
        /// <remarks/>
        public event Traer_UsuarioCompletedEventHandler Traer_UsuarioCompleted;
        
        /// <remarks/>
        public event Traer_TarifaCompletedEventHandler Traer_TarifaCompleted;
        
        /// <remarks/>
        public event LOGINCompletedEventHandler LOGINCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Man_Configuracion", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Man_Configuracion(string IdConfiguracion, string RUC, string RazonSocial, string Direccion, string Sede, string Ubicacion, string Capacidad, string TarifaDefecto, string TarifaCambio, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Man_Configuracion", new object[] {
                        IdConfiguracion,
                        RUC,
                        RazonSocial,
                        Direccion,
                        Sede,
                        Ubicacion,
                        Capacidad,
                        TarifaDefecto,
                        TarifaCambio,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Man_ConfiguracionAsync(string IdConfiguracion, string RUC, string RazonSocial, string Direccion, string Sede, string Ubicacion, string Capacidad, string TarifaDefecto, string TarifaCambio, string IdUsuario, string IP, string Opcion) {
            this.Man_ConfiguracionAsync(IdConfiguracion, RUC, RazonSocial, Direccion, Sede, Ubicacion, Capacidad, TarifaDefecto, TarifaCambio, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Man_ConfiguracionAsync(string IdConfiguracion, string RUC, string RazonSocial, string Direccion, string Sede, string Ubicacion, string Capacidad, string TarifaDefecto, string TarifaCambio, string IdUsuario, string IP, string Opcion, object userState) {
            if ((this.Man_ConfiguracionOperationCompleted == null)) {
                this.Man_ConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMan_ConfiguracionOperationCompleted);
            }
            this.InvokeAsync("Man_Configuracion", new object[] {
                        IdConfiguracion,
                        RUC,
                        RazonSocial,
                        Direccion,
                        Sede,
                        Ubicacion,
                        Capacidad,
                        TarifaDefecto,
                        TarifaCambio,
                        IdUsuario,
                        IP,
                        Opcion}, this.Man_ConfiguracionOperationCompleted, userState);
        }
        
        private void OnMan_ConfiguracionOperationCompleted(object arg) {
            if ((this.Man_ConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Man_ConfiguracionCompleted(this, new Man_ConfiguracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Man_Estacion", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Man_Estacion(string IdEstacion, string Descripcion, string NroAutorizacion, string NroMaquinaReg, string Producto, string PiePagina, string Impresora, string Excepcion, string SerieBoleta, string SerieFactura, string IdEstado, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Man_Estacion", new object[] {
                        IdEstacion,
                        Descripcion,
                        NroAutorizacion,
                        NroMaquinaReg,
                        Producto,
                        PiePagina,
                        Impresora,
                        Excepcion,
                        SerieBoleta,
                        SerieFactura,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Man_EstacionAsync(string IdEstacion, string Descripcion, string NroAutorizacion, string NroMaquinaReg, string Producto, string PiePagina, string Impresora, string Excepcion, string SerieBoleta, string SerieFactura, string IdEstado, string IdUsuario, string IP, string Opcion) {
            this.Man_EstacionAsync(IdEstacion, Descripcion, NroAutorizacion, NroMaquinaReg, Producto, PiePagina, Impresora, Excepcion, SerieBoleta, SerieFactura, IdEstado, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Man_EstacionAsync(string IdEstacion, string Descripcion, string NroAutorizacion, string NroMaquinaReg, string Producto, string PiePagina, string Impresora, string Excepcion, string SerieBoleta, string SerieFactura, string IdEstado, string IdUsuario, string IP, string Opcion, object userState) {
            if ((this.Man_EstacionOperationCompleted == null)) {
                this.Man_EstacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMan_EstacionOperationCompleted);
            }
            this.InvokeAsync("Man_Estacion", new object[] {
                        IdEstacion,
                        Descripcion,
                        NroAutorizacion,
                        NroMaquinaReg,
                        Producto,
                        PiePagina,
                        Impresora,
                        Excepcion,
                        SerieBoleta,
                        SerieFactura,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion}, this.Man_EstacionOperationCompleted, userState);
        }
        
        private void OnMan_EstacionOperationCompleted(object arg) {
            if ((this.Man_EstacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Man_EstacionCompleted(this, new Man_EstacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Man_TipoUsuario", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Man_TipoUsuario(string IdTipoUsuario, string Descripcion, string IdEstado, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Man_TipoUsuario", new object[] {
                        IdTipoUsuario,
                        Descripcion,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Man_TipoUsuarioAsync(string IdTipoUsuario, string Descripcion, string IdEstado, string IdUsuario, string IP, string Opcion) {
            this.Man_TipoUsuarioAsync(IdTipoUsuario, Descripcion, IdEstado, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Man_TipoUsuarioAsync(string IdTipoUsuario, string Descripcion, string IdEstado, string IdUsuario, string IP, string Opcion, object userState) {
            if ((this.Man_TipoUsuarioOperationCompleted == null)) {
                this.Man_TipoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMan_TipoUsuarioOperationCompleted);
            }
            this.InvokeAsync("Man_TipoUsuario", new object[] {
                        IdTipoUsuario,
                        Descripcion,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion}, this.Man_TipoUsuarioOperationCompleted, userState);
        }
        
        private void OnMan_TipoUsuarioOperationCompleted(object arg) {
            if ((this.Man_TipoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Man_TipoUsuarioCompleted(this, new Man_TipoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Man_Perfil", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Man_Perfil(string IdPerfil, string Formulario, string IdTipoUsuario, string Accion, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Man_Perfil", new object[] {
                        IdPerfil,
                        Formulario,
                        IdTipoUsuario,
                        Accion,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Man_PerfilAsync(string IdPerfil, string Formulario, string IdTipoUsuario, string Accion, string IdUsuario, string IP, string Opcion) {
            this.Man_PerfilAsync(IdPerfil, Formulario, IdTipoUsuario, Accion, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Man_PerfilAsync(string IdPerfil, string Formulario, string IdTipoUsuario, string Accion, string IdUsuario, string IP, string Opcion, object userState) {
            if ((this.Man_PerfilOperationCompleted == null)) {
                this.Man_PerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMan_PerfilOperationCompleted);
            }
            this.InvokeAsync("Man_Perfil", new object[] {
                        IdPerfil,
                        Formulario,
                        IdTipoUsuario,
                        Accion,
                        IdUsuario,
                        IP,
                        Opcion}, this.Man_PerfilOperationCompleted, userState);
        }
        
        private void OnMan_PerfilOperationCompleted(object arg) {
            if ((this.Man_PerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Man_PerfilCompleted(this, new Man_PerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Man_Usuario", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Man_Usuario(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion) {
            object[] results = this.Invoke("Man_Usuario", new object[] {
                        IdUsuario,
                        Nombre,
                        Apellido,
                        Usuario,
                        Contraseña,
                        IdTipoUsuario,
                        IdEstado,
                        IdUsu,
                        IP,
                        Opcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Man_UsuarioAsync(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion) {
            this.Man_UsuarioAsync(IdUsuario, Nombre, Apellido, Usuario, Contraseña, IdTipoUsuario, IdEstado, IdUsu, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Man_UsuarioAsync(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion, object userState) {
            if ((this.Man_UsuarioOperationCompleted == null)) {
                this.Man_UsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMan_UsuarioOperationCompleted);
            }
            this.InvokeAsync("Man_Usuario", new object[] {
                        IdUsuario,
                        Nombre,
                        Apellido,
                        Usuario,
                        Contraseña,
                        IdTipoUsuario,
                        IdEstado,
                        IdUsu,
                        IP,
                        Opcion}, this.Man_UsuarioOperationCompleted, userState);
        }
        
        private void OnMan_UsuarioOperationCompleted(object arg) {
            if ((this.Man_UsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Man_UsuarioCompleted(this, new Man_UsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Traer_Configuracion", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TablaConfiguracion[] Traer_Configuracion(string IdConfiguracion, string RUC, string RazonSocial, string Direccion, string Sede, string Ubicacion, string Capacidad, string TarifaDefecto, string TarifaCambio, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Traer_Configuracion", new object[] {
                        IdConfiguracion,
                        RUC,
                        RazonSocial,
                        Direccion,
                        Sede,
                        Ubicacion,
                        Capacidad,
                        TarifaDefecto,
                        TarifaCambio,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((TablaConfiguracion[])(results[0]));
        }
        
        /// <remarks/>
        public void Traer_ConfiguracionAsync(string IdConfiguracion, string RUC, string RazonSocial, string Direccion, string Sede, string Ubicacion, string Capacidad, string TarifaDefecto, string TarifaCambio, string IdUsuario, string IP, string Opcion) {
            this.Traer_ConfiguracionAsync(IdConfiguracion, RUC, RazonSocial, Direccion, Sede, Ubicacion, Capacidad, TarifaDefecto, TarifaCambio, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Traer_ConfiguracionAsync(string IdConfiguracion, string RUC, string RazonSocial, string Direccion, string Sede, string Ubicacion, string Capacidad, string TarifaDefecto, string TarifaCambio, string IdUsuario, string IP, string Opcion, object userState) {
            if ((this.Traer_ConfiguracionOperationCompleted == null)) {
                this.Traer_ConfiguracionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraer_ConfiguracionOperationCompleted);
            }
            this.InvokeAsync("Traer_Configuracion", new object[] {
                        IdConfiguracion,
                        RUC,
                        RazonSocial,
                        Direccion,
                        Sede,
                        Ubicacion,
                        Capacidad,
                        TarifaDefecto,
                        TarifaCambio,
                        IdUsuario,
                        IP,
                        Opcion}, this.Traer_ConfiguracionOperationCompleted, userState);
        }
        
        private void OnTraer_ConfiguracionOperationCompleted(object arg) {
            if ((this.Traer_ConfiguracionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Traer_ConfiguracionCompleted(this, new Traer_ConfiguracionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Traer_Estacion", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TablaEstacion[] Traer_Estacion(string IdEstacion, string Descripcion, string NroAutorizacion, string NroMaquinaReg, string Producto, string PiePagina, string Impresora, string Excepcion, string SerieBoleta, string SerieFactura, string IdEstado, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Traer_Estacion", new object[] {
                        IdEstacion,
                        Descripcion,
                        NroAutorizacion,
                        NroMaquinaReg,
                        Producto,
                        PiePagina,
                        Impresora,
                        Excepcion,
                        SerieBoleta,
                        SerieFactura,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((TablaEstacion[])(results[0]));
        }
        
        /// <remarks/>
        public void Traer_EstacionAsync(string IdEstacion, string Descripcion, string NroAutorizacion, string NroMaquinaReg, string Producto, string PiePagina, string Impresora, string Excepcion, string SerieBoleta, string SerieFactura, string IdEstado, string IdUsuario, string IP, string Opcion) {
            this.Traer_EstacionAsync(IdEstacion, Descripcion, NroAutorizacion, NroMaquinaReg, Producto, PiePagina, Impresora, Excepcion, SerieBoleta, SerieFactura, IdEstado, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Traer_EstacionAsync(string IdEstacion, string Descripcion, string NroAutorizacion, string NroMaquinaReg, string Producto, string PiePagina, string Impresora, string Excepcion, string SerieBoleta, string SerieFactura, string IdEstado, string IdUsuario, string IP, string Opcion, object userState) {
            if ((this.Traer_EstacionOperationCompleted == null)) {
                this.Traer_EstacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraer_EstacionOperationCompleted);
            }
            this.InvokeAsync("Traer_Estacion", new object[] {
                        IdEstacion,
                        Descripcion,
                        NroAutorizacion,
                        NroMaquinaReg,
                        Producto,
                        PiePagina,
                        Impresora,
                        Excepcion,
                        SerieBoleta,
                        SerieFactura,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion}, this.Traer_EstacionOperationCompleted, userState);
        }
        
        private void OnTraer_EstacionOperationCompleted(object arg) {
            if ((this.Traer_EstacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Traer_EstacionCompleted(this, new Traer_EstacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Traer_TipoUsuario", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TablaTipoUsuario[] Traer_TipoUsuario(string IdTipoUsuario, string Descripcion, string IdEstado, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Traer_TipoUsuario", new object[] {
                        IdTipoUsuario,
                        Descripcion,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((TablaTipoUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void Traer_TipoUsuarioAsync(string IdTipoUsuario, string Descripcion, string IdEstado, string IdUsuario, string IP, string Opcion) {
            this.Traer_TipoUsuarioAsync(IdTipoUsuario, Descripcion, IdEstado, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Traer_TipoUsuarioAsync(string IdTipoUsuario, string Descripcion, string IdEstado, string IdUsuario, string IP, string Opcion, object userState) {
            if ((this.Traer_TipoUsuarioOperationCompleted == null)) {
                this.Traer_TipoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraer_TipoUsuarioOperationCompleted);
            }
            this.InvokeAsync("Traer_TipoUsuario", new object[] {
                        IdTipoUsuario,
                        Descripcion,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion}, this.Traer_TipoUsuarioOperationCompleted, userState);
        }
        
        private void OnTraer_TipoUsuarioOperationCompleted(object arg) {
            if ((this.Traer_TipoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Traer_TipoUsuarioCompleted(this, new Traer_TipoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Traer_Usuario", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TablaUsuario[] Traer_Usuario(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion) {
            object[] results = this.Invoke("Traer_Usuario", new object[] {
                        IdUsuario,
                        Nombre,
                        Apellido,
                        Usuario,
                        Contraseña,
                        IdTipoUsuario,
                        IdEstado,
                        IdUsu,
                        IP,
                        Opcion});
            return ((TablaUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void Traer_UsuarioAsync(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion) {
            this.Traer_UsuarioAsync(IdUsuario, Nombre, Apellido, Usuario, Contraseña, IdTipoUsuario, IdEstado, IdUsu, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Traer_UsuarioAsync(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion, object userState) {
            if ((this.Traer_UsuarioOperationCompleted == null)) {
                this.Traer_UsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraer_UsuarioOperationCompleted);
            }
            this.InvokeAsync("Traer_Usuario", new object[] {
                        IdUsuario,
                        Nombre,
                        Apellido,
                        Usuario,
                        Contraseña,
                        IdTipoUsuario,
                        IdEstado,
                        IdUsu,
                        IP,
                        Opcion}, this.Traer_UsuarioOperationCompleted, userState);
        }
        
        private void OnTraer_UsuarioOperationCompleted(object arg) {
            if ((this.Traer_UsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Traer_UsuarioCompleted(this, new Traer_UsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/Traer_Tarifa", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TablaTarifa[] Traer_Tarifa(string IdTarifa, string Descripcion, string Monto, string Tiempo, string ToleranciaEntrada, string ToleranciaSalida, string MontoAdicional, string Editable, string Imprimir, string TipoTarifa, string ActivarTolerancia, string IdEstado, string IdUsuario, string IP, string Opcion) {
            object[] results = this.Invoke("Traer_Tarifa", new object[] {
                        IdTarifa,
                        Descripcion,
                        Monto,
                        Tiempo,
                        ToleranciaEntrada,
                        ToleranciaSalida,
                        MontoAdicional,
                        Editable,
                        Imprimir,
                        TipoTarifa,
                        ActivarTolerancia,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion});
            return ((TablaTarifa[])(results[0]));
        }
        
        /// <remarks/>
        public void Traer_TarifaAsync(string IdTarifa, string Descripcion, string Monto, string Tiempo, string ToleranciaEntrada, string ToleranciaSalida, string MontoAdicional, string Editable, string Imprimir, string TipoTarifa, string ActivarTolerancia, string IdEstado, string IdUsuario, string IP, string Opcion) {
            this.Traer_TarifaAsync(IdTarifa, Descripcion, Monto, Tiempo, ToleranciaEntrada, ToleranciaSalida, MontoAdicional, Editable, Imprimir, TipoTarifa, ActivarTolerancia, IdEstado, IdUsuario, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void Traer_TarifaAsync(
                    string IdTarifa, 
                    string Descripcion, 
                    string Monto, 
                    string Tiempo, 
                    string ToleranciaEntrada, 
                    string ToleranciaSalida, 
                    string MontoAdicional, 
                    string Editable, 
                    string Imprimir, 
                    string TipoTarifa, 
                    string ActivarTolerancia, 
                    string IdEstado, 
                    string IdUsuario, 
                    string IP, 
                    string Opcion, 
                    object userState) {
            if ((this.Traer_TarifaOperationCompleted == null)) {
                this.Traer_TarifaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTraer_TarifaOperationCompleted);
            }
            this.InvokeAsync("Traer_Tarifa", new object[] {
                        IdTarifa,
                        Descripcion,
                        Monto,
                        Tiempo,
                        ToleranciaEntrada,
                        ToleranciaSalida,
                        MontoAdicional,
                        Editable,
                        Imprimir,
                        TipoTarifa,
                        ActivarTolerancia,
                        IdEstado,
                        IdUsuario,
                        IP,
                        Opcion}, this.Traer_TarifaOperationCompleted, userState);
        }
        
        private void OnTraer_TarifaOperationCompleted(object arg) {
            if ((this.Traer_TarifaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Traer_TarifaCompleted(this, new Traer_TarifaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/WebService/LOGIN", RequestNamespace="http://localhost/WebService", ResponseNamespace="http://localhost/WebService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TablaUsuario[] LOGIN(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion) {
            object[] results = this.Invoke("LOGIN", new object[] {
                        IdUsuario,
                        Nombre,
                        Apellido,
                        Usuario,
                        Contraseña,
                        IdTipoUsuario,
                        IdEstado,
                        IdUsu,
                        IP,
                        Opcion});
            return ((TablaUsuario[])(results[0]));
        }
        
        /// <remarks/>
        public void LOGINAsync(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion) {
            this.LOGINAsync(IdUsuario, Nombre, Apellido, Usuario, Contraseña, IdTipoUsuario, IdEstado, IdUsu, IP, Opcion, null);
        }
        
        /// <remarks/>
        public void LOGINAsync(string IdUsuario, string Nombre, string Apellido, string Usuario, string Contraseña, string IdTipoUsuario, string IdEstado, string IdUsu, string IP, string Opcion, object userState) {
            if ((this.LOGINOperationCompleted == null)) {
                this.LOGINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLOGINOperationCompleted);
            }
            this.InvokeAsync("LOGIN", new object[] {
                        IdUsuario,
                        Nombre,
                        Apellido,
                        Usuario,
                        Contraseña,
                        IdTipoUsuario,
                        IdEstado,
                        IdUsu,
                        IP,
                        Opcion}, this.LOGINOperationCompleted, userState);
        }
        
        private void OnLOGINOperationCompleted(object arg) {
            if ((this.LOGINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LOGINCompleted(this, new LOGINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WebService")]
    public partial class TablaConfiguracion {
        
        private string idField;
        
        private string rUCField;
        
        private string razonSocialField;
        
        private string direccionField;
        
        private string sedeField;
        
        private string ubicacionField;
        
        private string capacidadField;
        
        private string tarifaDefectoField;
        
        private string tarifaCambioField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string RUC {
            get {
                return this.rUCField;
            }
            set {
                this.rUCField = value;
            }
        }
        
        /// <remarks/>
        public string RazonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        public string Sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
            }
        }
        
        /// <remarks/>
        public string Ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
            }
        }
        
        /// <remarks/>
        public string Capacidad {
            get {
                return this.capacidadField;
            }
            set {
                this.capacidadField = value;
            }
        }
        
        /// <remarks/>
        public string TarifaDefecto {
            get {
                return this.tarifaDefectoField;
            }
            set {
                this.tarifaDefectoField = value;
            }
        }
        
        /// <remarks/>
        public string TarifaCambio {
            get {
                return this.tarifaCambioField;
            }
            set {
                this.tarifaCambioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WebService")]
    public partial class TablaTarifa {
        
        private string idField;
        
        private string descripcionField;
        
        private string montoField;
        
        private string tiempoField;
        
        private string toleranciaEntradaField;
        
        private string toleranciaSalidaField;
        
        private string montoAdicionalField;
        
        private string editableField;
        
        private string imprimirField;
        
        private string tipoTarifaField;
        
        private string activarToleranciaField;
        
        private string estadoField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        public string Tiempo {
            get {
                return this.tiempoField;
            }
            set {
                this.tiempoField = value;
            }
        }
        
        /// <remarks/>
        public string ToleranciaEntrada {
            get {
                return this.toleranciaEntradaField;
            }
            set {
                this.toleranciaEntradaField = value;
            }
        }
        
        /// <remarks/>
        public string ToleranciaSalida {
            get {
                return this.toleranciaSalidaField;
            }
            set {
                this.toleranciaSalidaField = value;
            }
        }
        
        /// <remarks/>
        public string MontoAdicional {
            get {
                return this.montoAdicionalField;
            }
            set {
                this.montoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        public string Editable {
            get {
                return this.editableField;
            }
            set {
                this.editableField = value;
            }
        }
        
        /// <remarks/>
        public string Imprimir {
            get {
                return this.imprimirField;
            }
            set {
                this.imprimirField = value;
            }
        }
        
        /// <remarks/>
        public string TipoTarifa {
            get {
                return this.tipoTarifaField;
            }
            set {
                this.tipoTarifaField = value;
            }
        }
        
        /// <remarks/>
        public string ActivarTolerancia {
            get {
                return this.activarToleranciaField;
            }
            set {
                this.activarToleranciaField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WebService")]
    public partial class TablaUsuario {
        
        private string idField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string usuarioField;
        
        private string contraseñaField;
        
        private string tipoUsuarioField;
        
        private string estadoField;
        
        private string empresaField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string Apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
        
        /// <remarks/>
        public string TipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Empresa {
            get {
                return this.empresaField;
            }
            set {
                this.empresaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WebService")]
    public partial class TablaTipoUsuario {
        
        private string idField;
        
        private string descripcionField;
        
        private string estadoField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/WebService")]
    public partial class TablaEstacion {
        
        private string idField;
        
        private string descripcionField;
        
        private string nroAutorizacionField;
        
        private string nroMaquinaRegField;
        
        private string productoField;
        
        private string piePaginaField;
        
        private string impresoraField;
        
        private string excepcionField;
        
        private string serieBoletaField;
        
        private string serieFacturaField;
        
        private string estadoField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string NroAutorizacion {
            get {
                return this.nroAutorizacionField;
            }
            set {
                this.nroAutorizacionField = value;
            }
        }
        
        /// <remarks/>
        public string NroMaquinaReg {
            get {
                return this.nroMaquinaRegField;
            }
            set {
                this.nroMaquinaRegField = value;
            }
        }
        
        /// <remarks/>
        public string Producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
            }
        }
        
        /// <remarks/>
        public string PiePagina {
            get {
                return this.piePaginaField;
            }
            set {
                this.piePaginaField = value;
            }
        }
        
        /// <remarks/>
        public string Impresora {
            get {
                return this.impresoraField;
            }
            set {
                this.impresoraField = value;
            }
        }
        
        /// <remarks/>
        public string Excepcion {
            get {
                return this.excepcionField;
            }
            set {
                this.excepcionField = value;
            }
        }
        
        /// <remarks/>
        public string SerieBoleta {
            get {
                return this.serieBoletaField;
            }
            set {
                this.serieBoletaField = value;
            }
        }
        
        /// <remarks/>
        public string SerieFactura {
            get {
                return this.serieFacturaField;
            }
            set {
                this.serieFacturaField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Man_ConfiguracionCompletedEventHandler(object sender, Man_ConfiguracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Man_ConfiguracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Man_ConfiguracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Man_EstacionCompletedEventHandler(object sender, Man_EstacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Man_EstacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Man_EstacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Man_TipoUsuarioCompletedEventHandler(object sender, Man_TipoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Man_TipoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Man_TipoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Man_PerfilCompletedEventHandler(object sender, Man_PerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Man_PerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Man_PerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Man_UsuarioCompletedEventHandler(object sender, Man_UsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Man_UsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Man_UsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Traer_ConfiguracionCompletedEventHandler(object sender, Traer_ConfiguracionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Traer_ConfiguracionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Traer_ConfiguracionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TablaConfiguracion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TablaConfiguracion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Traer_EstacionCompletedEventHandler(object sender, Traer_EstacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Traer_EstacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Traer_EstacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TablaEstacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TablaEstacion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Traer_TipoUsuarioCompletedEventHandler(object sender, Traer_TipoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Traer_TipoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Traer_TipoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TablaTipoUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TablaTipoUsuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Traer_UsuarioCompletedEventHandler(object sender, Traer_UsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Traer_UsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Traer_UsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TablaUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TablaUsuario[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void Traer_TarifaCompletedEventHandler(object sender, Traer_TarifaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Traer_TarifaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Traer_TarifaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TablaTarifa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TablaTarifa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void LOGINCompletedEventHandler(object sender, LOGINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LOGINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LOGINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TablaUsuario[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TablaUsuario[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591